
services:

  back:
    build: ./server
    restart: always
    expose:
      - 3001
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  front:
    build: ./next-app
    restart: always
    links:
      - back
    depends_on:
      - back
    ports:
      - 3010:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.mycustomcontainer.rule=PathPrefix(`/watch-tonight`)"
